# Generated by Django 2.2.7 on 2021-05-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfLaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theses', models.CharField(max_length=255, verbose_name='Тезисы')),
                ('legal_flag', models.CharField(max_length=255, verbose_name='Юридический флаг')),
            ],
            options={
                'verbose_name': 'Область права',
            },
        ),
    ]
