# Generated by Django 2.2.7 on 2021-05-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210505_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementsofclaim',
            name='document',
            field=models.ImageField(upload_to='documents/%Y/%m/%d/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='statementsofclaim',
            name='regulations',
            field=models.ManyToManyField(to='bot.Regulations', verbose_name='Правила'),
        ),
    ]
