# Generated by Django 2.2.7 on 2021-05-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210511_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementsofclaim',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Документ'),
        ),
    ]
