# Generated by Django 2.2.7 on 2021-05-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210511_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='main_question',
            field=models.IntegerField(default=0, verbose_name='Подвопросы вопрос'),
        ),
    ]
