# Generated by Django 2.2.7 on 2021-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210518_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='main_question',
            field=models.IntegerField(default=0, verbose_name='Подвопросы'),
        ),
    ]
