# Generated by Django 2.2.7 on 2021-05-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210518_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementsofclaim',
            name='title',
            field=models.CharField(default='none', max_length=255, verbose_name='Название'),
        ),
    ]
